/*
-- Query: SELECT * FROM donate_db.projects
LIMIT 0, 1000

-- Date: 2017-03-24 01:01
*/
INSERT INTO `projects` (`id`,`name`,`description`,`imageUrl`,`donations`,`goal`,`createdAt`,`updatedAt`,`UserId`) VALUES (1,'Save The Trees','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','http://lorempixel.com/350/350/sports',0,'1000','2017-03-23 15:30:00','2017-03-23 15:30:00',1);
INSERT INTO `projects` (`id`,`name`,`description`,`imageUrl`,`donations`,`goal`,`createdAt`,`updatedAt`,`UserId`) VALUES (2,'Feed Hungry Children','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','http://lorempixel.com/350/350/animals',0,'2000','2017-03-23 15:30:00','2017-03-23 15:30:00',3);
INSERT INTO `projects` (`id`,`name`,`description`,`imageUrl`,`donations`,`goal`,`createdAt`,`updatedAt`,`UserId`) VALUES (3,'Education For All','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','http://lorempixel.com/350/350/business',0,'3500','2017-03-23 15:30:00','2017-03-23 15:30:00',3);
INSERT INTO `projects` (`id`,`name`,`description`,`imageUrl`,`donations`,`goal`,`createdAt`,`updatedAt`,`UserId`) VALUES (4,'Canned Goods For Homeless','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','http://lorempixel.com/350/350/people',0,'48000','2017-03-23 15:30:00','2017-03-23 15:30:00',2);
INSERT INTO `projects` (`id`,`name`,`description`,`imageUrl`,`donations`,`goal`,`createdAt`,`updatedAt`,`UserId`) VALUES (5,'Brain Surgery for Chris','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','http://lorempixel.com/350/350/nature',0,'900','2017-03-23 15:30:00','2017-03-23 15:30:00',1);
INSERT INTO `projects` (`id`,`name`,`description`,`imageUrl`,`donations`,`goal`,`createdAt`,`updatedAt`,`UserId`) VALUES (6,'Stop Polution','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','http://lorempixel.com/350/350/food',0,'250','2017-03-23 15:30:00','2017-03-23 15:30:00',1);
